#!/usr/bin/env bash

set -euo pipefail

SCRIPT_DIR="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd -- "$SCRIPT_DIR/.." && pwd)"

if [[ -f "$REPO_ROOT/.env" ]]; then
  set -a
  # shellcheck disable=SC1091
  source "$REPO_ROOT/.env"
  set +a
fi

API_BASE_URL="${API_BASE_URL:-http://localhost:8000}"
REDIS_CONTAINER="${REDIS_CONTAINER:-ai_redis}"
POSTGRES_CONTAINER="${POSTGRES_CONTAINER:-ai_postgres}"
BACKEND_CONTAINER="${BACKEND_CONTAINER:-ai_backend}"
WORKER_CONTAINER="${WORKER_CONTAINER:-ai_worker}"
TASK_QUEUE_NAME="${TASK_QUEUE_NAME:-tasks:queue}"
POSTGRES_USER="${POSTGRES_USER:-ai_user}"
POSTGRES_DB="${POSTGRES_DB:-ai_assistant}"

fail() {
  echo "FAIL: $1" >&2
  exit 1
}

require_cmd() {
  command -v "$1" >/dev/null 2>&1 || fail "required command not found: $1"
}

require_cmd curl
require_cmd docker
require_cmd python3

list_backend_worker_runtime_pids() {
  docker exec -i "$BACKEND_CONTAINER" python3 - <<'PY'
import os

for pid in sorted(os.listdir("/proc"), key=lambda x: int(x) if x.isdigit() else 10**9):
    if not pid.isdigit():
        continue
    try:
        cmdline = open(f"/proc/{pid}/cmdline", "rb").read().decode("utf-8", "ignore").replace("\x00", " ").strip()
    except Exception:
        continue
    if "python -m app.worker_runtime" in cmdline:
        print(pid)
PY
}

post_email() {
  local payload="$1"
  curl -fsS -X POST "$API_BASE_URL/email-intake/gmail/messages" \
    -H "Content-Type: application/json" \
    -d "$payload"
}

json_get() {
  local payload="$1"
  local expr="$2"
  printf '%s' "$payload" | python3 -c "import json,sys; data=json.load(sys.stdin); print($expr)"
}

docker inspect "$REDIS_CONTAINER" >/dev/null 2>&1 || fail "redis container not found: $REDIS_CONTAINER"
docker inspect "$POSTGRES_CONTAINER" >/dev/null 2>&1 || fail "postgres container not found: $POSTGRES_CONTAINER"
docker inspect "$BACKEND_CONTAINER" >/dev/null 2>&1 || fail "backend container not found: $BACKEND_CONTAINER"

curl -fsS "$API_BASE_URL/health" >/dev/null || fail "backend healthcheck failed: $API_BASE_URL/health"
echo "PASS: backend healthcheck is reachable"

if docker inspect "$WORKER_CONTAINER" >/dev/null 2>&1; then
  worker_running="$(
    docker inspect -f '{{.State.Running}}' "$WORKER_CONTAINER" 2>/dev/null || echo false
  )"
  [[ "$worker_running" != "true" ]] || fail "email intake smoke requires ai_worker to be stopped: $WORKER_CONTAINER"
fi
echo "PASS: compose worker is not running"

manual_worker_pids="$(list_backend_worker_runtime_pids)"
[[ -z "$manual_worker_pids" ]] || fail "email intake smoke requires no manual worker inside backend (found pids: $manual_worker_pids)"
echo "PASS: no manual worker is running inside backend"

run_id="$(date -u +%Y%m%dT%H%M%SZ)"
mailbox="ops@example.com"
curl -fsS \
  -X PUT "$API_BASE_URL/mailboxes/gmail/$mailbox/policy" \
  -H "Content-Type: application/json" \
  -d '{"scope_mode":"all","triage_thresholds":{"light_min":25,"deep_min":60,"deep_with_attachment_min":40,"uncertain_band":0},"attachment_policy":{"download_for":["deep"],"max_attachments":5},"rollout_mode":"approval_only_for_deep"}' >/dev/null \
  || fail "failed to set deterministic gmail intake smoke policy"

ignore_response="$(post_email "$(cat <<JSON
{"mailbox":"$mailbox","provider_message_id":"gmail-ignore-$run_id","internet_message_id":"<ignore-$run_id@example.com>","from_address":"no-reply@vendor.example","subject":"Automatic Reply: your ticket","snippet":"Automatic reply generated by mailbox","labels":["INBOX"],"attachments":[]}
JSON
)")" || fail "ignore intake failed"
[[ "$(json_get "$ignore_response" "data['routing_decision']")" == "ignore" ]] || fail "ignore case did not route to ignore"
[[ "$(json_get "$ignore_response" "data['prefilter_status']")" == "ignored" ]] || fail "ignore case prefilter_status mismatch"
echo "PASS: ignore case routed correctly"

light_response="$(post_email "$(cat <<JSON
{"mailbox":"$mailbox","provider_message_id":"gmail-light-$run_id","internet_message_id":"<light-$run_id@example.com>","from_address":"pm@example.net","subject":"Request: review weekly status digest","snippet":"Please review the weekly digest before tomorrow so we can prepare the next summary.","labels":["INBOX"],"attachments":[]}
JSON
)")" || fail "light intake failed"
[[ "$(json_get "$light_response" "data['routing_decision']")" == "light" ]] || fail "light case did not route to light"
[[ "$(json_get "$light_response" "data['task_id'] or ''")" == "" ]] || fail "light case unexpectedly created task"
echo "PASS: light case routed correctly"

deep_response="$(post_email "$(cat <<JSON
{"mailbox":"$mailbox","provider_message_id":"gmail-deep-$run_id","internet_message_id":"<deep-$run_id@example.com>","from_address":"client@example.net","subject":"Action required: approve invoice today","snippet":"Please review the invoice and approve payment before the deadline tomorrow morning.","labels":["INBOX","IMPORTANT"],"attachments":[]}
JSON
)")" || fail "deep intake failed"
deep_task_id="$(json_get "$deep_response" "data['task_id'] or ''")"
[[ "$(json_get "$deep_response" "data['routing_decision']")" == "deep" ]] || fail "deep case did not route to deep"
[[ -n "$deep_task_id" ]] || fail "deep case did not create task"
echo "PASS: deep case routed correctly"

attachment_response="$(post_email "$(cat <<JSON
{"mailbox":"$mailbox","provider_message_id":"gmail-attachment-$run_id","internet_message_id":"<attachment-$run_id@example.com>","from_address":"legal@example.net","subject":"Contract for review","snippet":"Attached contract needs review and approval this week.","labels":["INBOX"],"attachments":[{"provider_attachment_id":"att-1","filename":"contract.pdf","mime_type":"application/pdf","file_size":2048,"is_inline":false}]}
JSON
)")" || fail "attachment intake failed"
attachment_task_id="$(json_get "$attachment_response" "data['task_id'] or ''")"
attachment_email_id="$(json_get "$attachment_response" "data['id']")"
[[ "$(json_get "$attachment_response" "data['routing_decision']")" == "deep" ]] || fail "attachment case did not route to deep"
[[ "$(json_get "$attachment_response" "data['attachments_count']")" == "1" ]] || fail "attachment count mismatch"
[[ "$(json_get "$attachment_response" "len(data['attachments'])")" == "1" ]] || fail "attachment metadata was not persisted"
[[ -n "$attachment_task_id" ]] || fail "attachment case did not create task"
echo "PASS: attachment case routed correctly"

duplicate_response="$(post_email "$(cat <<JSON
{"mailbox":"$mailbox","provider_message_id":"gmail-attachment-$run_id","internet_message_id":"<attachment-$run_id@example.com>","from_address":"legal@example.net","subject":"Contract for review","snippet":"Attached contract needs review and approval this week.","labels":["INBOX"],"attachments":[{"provider_attachment_id":"att-1b","filename":"contract-copy.pdf","mime_type":"application/pdf","file_size":2049,"is_inline":false}]}
JSON
)")" || fail "duplicate intake failed"
[[ "$(json_get "$duplicate_response" "data['routing_decision']")" == "ignore" ]] || fail "duplicate case should route to ignore"
[[ "$(json_get "$duplicate_response" "data['duplicate_of_email_id']")" == "$attachment_email_id" ]] || fail "duplicate case did not point to original email"
[[ "$(json_get "$duplicate_response" "data['task_id'] or ''")" == "" ]] || fail "duplicate case unexpectedly created task"
echo "PASS: duplicate case routed correctly"

for task_id in "$deep_task_id" "$attachment_task_id"; do
  task_response="$(curl -fsS "$API_BASE_URL/tasks/$task_id")" || fail "GET /tasks/$task_id failed"
  [[ "$(json_get "$task_response" "data['status']")" == "queued" ]] || fail "task $task_id is not queued"
  docker exec "$REDIS_CONTAINER" redis-cli --raw LRANGE "$TASK_QUEUE_NAME" 0 -1 \
    | grep -Fxq "$task_id" \
    || fail "task $task_id not found in Redis queue"
done
echo "PASS: deep-only tasks were queued"

db_counts="$(
  docker exec "$POSTGRES_CONTAINER" psql -U "$POSTGRES_USER" -d "$POSTGRES_DB" -tAc \
    "SELECT COUNT(*), COUNT(task_id), COUNT(duplicate_of_email_id) FROM email_sources WHERE provider_message_id LIKE 'gmail-%-$run_id';"
)"
[[ "$(printf '%s' "$db_counts" | tr -d ' ')" == "5|2|1" ]] || fail "unexpected email_sources counts: $db_counts"
echo "PASS: PostgreSQL email source counts match expected ignore/light/deep/attachment/duplicate flow"

echo "SMOKE EMAIL INTAKE TEST PASSED"
